[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lspattern"
version = "0.1.0"
requires-python = ">=3.9, <3.14"
dynamic = ["dependencies", "optional-dependencies"]