name: ruff

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/ruff-action@v3
        with:
          version-file: requirements-dev.txt
          args: check ./graphix_zx ./tests ./examples

      - run: ruff format --check --diff
